apiversion: apps/v1
kind: Deployment
metadata:
   name: node app-deployment
   labels:
	app: nodeapp
spec:
   replicas: 1
   selector:
	matchlabels:
		app: nodeapp
   template:
     metadata:
	labels:
	   app: nodeapp
     spec:
	containers:
	- name: nodeserver
	  image: satyaprakash33372/nodeapp:latest
	  ports:
	  - containerPort: 3000


---

apiversion: v1
kind: Service
metadata:
   name: node app-service
spec:
  selector:
	app: nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodeport: 31110
